### ISSUE TITLE
ubuntu-printing-app does not have a maintainer

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/ubuntu-printing-app#1]
No one is currently maintaining this app. If you would like to become the maintainer, please reply to this issue or get a hold of us via another method.

The app maintainers will be responsible for coordinating the following (doing it yourself is still coordinating, if you prefer that):

* Triaging bugs
* Fixing bugs
* Vetting and implementing enhancement requests
* Corresponding with the UBports project regarding the app's progress
* Requesting bounties be posted for the app
* Dealing with the bane of my existence, printers.

**Comment by Flohack74** [comment]
I think we can close this. This App is a new feature that we could implement, and @ahayzen is necessary for this by all means, so Andrew if you agree we assume that you are the only one that can maintain it, and would ask for a positive yess :)

**Comment by ahayzen** [comment]
@Flohack74 Yes happy to maintain :-) Please see https://github.com/ubports/music-app/issues/1#issuecomment-306445691

**Comment by Flohack74** [comment]
Alright! Saw your comment. Actually I think no one can do better decisions than the maintainers themselves, so I think you will have your voice about SDK features :)
